In [3]:
import os

print(os.getcwd())

c:\Users\ASUS\OneDrive\Desktop\nifty100_project\notebook

In [4]:
os.chdir("..")

print(os.getcwd())

c:\Users\ASUS\OneDrive\Desktop\nifty100_project

In [5]:
os.listdir("data/raw")

['analysis.xlsx',
 'balancesheet.xlsx',
 'cashflow.xlsx',
 'companies.xlsx',
 'documents.xlsx',
 'financial_ratios.xlsx',
 'market_cap.xlsx',
 'peer_groups.xlsx',
 'profitandloss.xlsx',
 'prosandcons.xlsx',
 'sectors.xlsx',
 'stock_prices.xlsx']

In [6]:
import sqlite3

conn = sqlite3.connect("database/nifty100.db")

cursor = conn.cursor()

cursor.execute("""
SELECT name
FROM sqlite_master
WHERE type='table'
""")

print(cursor.fetchall())

conn.close()

[('analysis',), ('balancesheet',), ('cashflow',), ('companies',), ('documents',), ('financial_ratios',), ('market_cap',), ('peer_groups',), ('profitandloss',), ('prosandcons',), ('sectors',), ('stock_prices',)]

In [7]:
import pandas as pd

df = pd.read_excel("data/raw/companies.xlsx")

df.head()

,Mkt Fintech — Nifty 100 | Companies | 92 records,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,id,company_logo,company_name,chart_link,about_company,website,nse_profile,bse_profile,face_value,book_value,roce_percentage,roe_percentage
1,ABB,https://mkt.in/static/mkt-icons/nifty100/ABB.png,Abbott India Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,Abbott India Ltd is one of the leading multina...,https://www.abbott.co.in/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/abb...,10,1657,46,34.9
2,ADANIENSOL,https://m.economictimes.com/thumb/msid-1173715...,Adani Energy Solutions Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,"AESL, part of the Adani portfolio, is a multid...",https://www.adanienergysolutions.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,10,175,9,8.59
3,ADANIENT,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Enterprises Ltd,https://in.tradingview.com/chart/?symbol=ADANIENT,Adani Enterprises Ltd is an Indian multination...,https://www.adanienterprises.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,1,363,11.6,13.64
4,ADANIGREEN,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Green Energy Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,"Adani Green Energy Limited, incorporated in 20...",http://www.adanigreenenergy.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,10,67,96.5,14.7

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 12 columns):
 #   Column                                                Non-Null Count  Dtype
---  ------                                                --------------  -----
 0   Mkt Fintech — Nifty 100  |  Companies  |  92 records  93 non-null     object
 1   Unnamed: 1                                            92 non-null     object
 2   Unnamed: 2                                            93 non-null     object
 3   Unnamed: 3                                            93 non-null     object
 4   Unnamed: 4                                            93 non-null     object
 5   Unnamed: 5                                            92 non-null     object
 6   Unnamed: 6                                            92 non-null     object
 7   Unnamed: 7                                            92 non-null     object
 8   Unnamed: 8                                            92 non-null     object
 9   Unnamed: 9                                            92 non-null     object
 10  Unnamed: 10                                           92 non-null     object
 11  Unnamed: 11                                           91 non-null     object
dtypes: object(12)
memory usage: 8.8+ KB

In [9]:
df.isnull().sum()

Mkt Fintech — Nifty 100  |  Companies  |  92 records    0
Unnamed: 1                                              1
Unnamed: 2                                              0
Unnamed: 3                                              0
Unnamed: 4                                              0
Unnamed: 5                                              1
Unnamed: 6                                              1
Unnamed: 7                                              1
Unnamed: 8                                              1
Unnamed: 9                                              1
Unnamed: 10                                             1
Unnamed: 11                                             2
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.describe()

,Mkt Fintech — Nifty 100 | Companies | 92 records,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
count,93,92,93,93,93,92,92,92,92,92,92.0,91.0
unique,93,91,93,55,93,91,92,92,5,85,85.0,86.0
top,id,https://mkt.in/static/mkt-icons/nifty100/HEROM...,company_name,https://in.tradingview.com/chart/qGsydD2w/?sym...,about_company,https://www.bajajfinserv.in/,nse_profile,bse_profile,10,275,13.2,20.2
freq,1,2,1,39,1,2,1,1,31,3,3.0,2.0