In [2]:
import os
print(os.getcwd())

c:\Users\ASUS\OneDrive\Desktop\nifty100_project\notebook

In [ ]:
import os

os.chdir(r"C:\Users\ASUS\OneDrive\Desktop\nifty100_project")

print(os.getcwd())

C:\Users\ASUS\OneDrive\Desktop\nifty100_project

In [5]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("database/nifty100.db")

In [6]:
tables = pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table'
""", conn)

tables

                name
0           analysis
1       balancesheet
2           cashflow
3          companies
4          documents
5   financial_ratios
6         market_cap
7        peer_groups
8      profitandloss
9        prosandcons
10           sectors
11      stock_prices

In [7]:
for table in tables["name"]:

    df = pd.read_sql(
        f"SELECT * FROM {table}",
        conn
    )

    print("\n===================")
    print(table)

    print("Rows:", len(df))
    print("Columns:", len(df.columns))

    print("Null Values:")
    print(df.isnull().sum().sum())

    print("Duplicate Rows:")
    print(df.duplicated().sum())

===================
analysis
Rows: 21
Columns: 6
Null Values:
0
Duplicate Rows:
0

===================
balancesheet
Rows: 1313
Columns: 13
Null Values:
0
Duplicate Rows:
0

===================
cashflow
Rows: 1188
Columns: 7
Null Values:
8
Duplicate Rows:
0

===================
companies
Rows: 93
Columns: 12
Null Values:
9
Duplicate Rows:
0

===================
documents
Rows: 1586
Columns: 4
Null Values:
52
Duplicate Rows:
0

===================
financial_ratios
Rows: 1184
Columns: 16
Null Values:
170
Duplicate Rows:
0

===================
market_cap
Rows: 552
Columns: 9
Null Values:
0
Duplicate Rows:
0

===================
peer_groups
Rows: 56
Columns: 4
Null Values:
0
Duplicate Rows:
0

===================
profitandloss
Rows: 1277
Columns: 15
Null Values:
231
Duplicate Rows:
0

===================
prosandcons
Rows: 17
Columns: 4
Null Values:
6
Duplicate Rows:
0

===================
sectors
Rows: 92
Columns: 6
Null Values:
0
Duplicate Rows:
0

===================
stock_prices
Rows: 5520
Columns: 9
Null Values:
0
Duplicate Rows:
0

In [8]:
audit = []

for table in tables["name"]:

    df = pd.read_sql(
        f"SELECT * FROM {table}",
        conn
    )

    audit.append({
        "table_name": table,
        "rows": len(df),
        "columns": len(df.columns),
        "null_values": df.isnull().sum().sum(),
        "duplicates": df.duplicated().sum()
    })

audit_df = pd.DataFrame(audit)

audit_df.to_csv(
    "reports/load_audit.csv",
    index=False
)

audit_df

          table_name  rows  columns  null_values  duplicates
0           analysis    21        6            0           0
1       balancesheet  1313       13            0           0
2           cashflow  1188        7            8           0
3          companies    93       12            9           0
4          documents  1586        4           52           0
5   financial_ratios  1184       16          170           0
6         market_cap   552        9            0           0
7        peer_groups    56        4            0           0
8      profitandloss  1277       15          231           0
9        prosandcons    17        4            6           0
10           sectors    92        6            0           0
11      stock_prices  5520        9            0           0