In [2]:
import os

os.chdir(r"C:\Users\ASUS\OneDrive\Desktop\nifty100_project")

print(os.getcwd())

C:\Users\ASUS\OneDrive\Desktop\nifty100_project

In [7]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("database/nifty100.db")

print("Connected")

Connected

In [8]:
companies = pd.read_sql(
    "SELECT * FROM companies",
    conn
)

print(companies.shape)
companies.head()

(93, 12)

,Mkt Fintech — Nifty 100 | Companies | 92 records,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,id,company_logo,company_name,chart_link,about_company,website,nse_profile,bse_profile,face_value,book_value,roce_percentage,roe_percentage
1,ABB,https://mkt.in/static/mkt-icons/nifty100/ABB.png,Abbott India Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,Abbott India Ltd is one of the leading multina...,https://www.abbott.co.in/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/abb...,10,1657,46,34.9
2,ADANIENSOL,https://m.economictimes.com/thumb/msid-1173715...,Adani Energy Solutions Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,"AESL, part of the Adani portfolio, is a multid...",https://www.adanienergysolutions.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,10,175,9,8.59
3,ADANIENT,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Enterprises Ltd,https://in.tradingview.com/chart/?symbol=ADANIENT,Adani Enterprises Ltd is an Indian multination...,https://www.adanienterprises.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,1,363,11.6,13.64
4,ADANIGREEN,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Green Energy Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,"Adani Green Energy Limited, incorporated in 20...",http://www.adanigreenenergy.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,10,67,96.5,14.7

In [9]:
companies.columns = companies.iloc[0]

companies = companies[1:]

companies.head()

,id,company_logo,company_name,chart_link,about_company,website,nse_profile,bse_profile,face_value,book_value,roce_percentage,roe_percentage
1,ABB,https://mkt.in/static/mkt-icons/nifty100/ABB.png,Abbott India Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,Abbott India Ltd is one of the leading multina...,https://www.abbott.co.in/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/abb...,10,1657,46,34.9
2,ADANIENSOL,https://m.economictimes.com/thumb/msid-1173715...,Adani Energy Solutions Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,"AESL, part of the Adani portfolio, is a multid...",https://www.adanienergysolutions.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,10,175,9,8.59
3,ADANIENT,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Enterprises Ltd,https://in.tradingview.com/chart/?symbol=ADANIENT,Adani Enterprises Ltd is an Indian multination...,https://www.adanienterprises.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,1,363,11.6,13.64
4,ADANIGREEN,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Green Energy Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,"Adani Green Energy Limited, incorporated in 20...",http://www.adanigreenenergy.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,10,67,96.5,14.7
5,ADANIPORTS,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Ports & Special Economic Zone Ltd\n,https://in.tradingview.com/chart/?symbol=NSE%3...,Adani Ports & Special Economic Zone is in the ...,http://www.adaniports.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,2,265,12.9,18.1

In [10]:
sample_companies = companies[
    ["id","company_name"]
].sample(5)

sample_companies

0           id                   company_name
92    TVSMOTOR          TVS Motor Company Ltd
90  TORNTPHARM    Torrent Pharmaceuticals Ltd
87         TCS  Tata Consultancy Services Ltd
18  BHARTIARTL              Bharti Airtel Ltd
13  BAJAJFINSV              Bajaj Finserv Ltd

In [11]:
tables = [
    "companies",
    "profitandloss",
    "balancesheet",
    "cashflow",
    "financial_ratios",
    "stock_prices"
]

for table in tables:

    df = pd.read_sql(
        f"SELECT * FROM {table}",
        conn
    )

    print(table, df.shape)

companies (93, 12)
profitandloss (1277, 15)
balancesheet (1313, 13)
cashflow (1188, 7)
financial_ratios (1184, 16)
stock_prices (5520, 9)

In [12]:
import pandas as pd
import sqlite3

conn = sqlite3.connect("database/nifty100.db")

tables = pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table'
""", conn)

audit = []

for table in tables["name"]:
    df = pd.read_sql(f"SELECT * FROM {table}", conn)

    audit.append([
        table,
        len(df),
        len(df.columns),
        df.isnull().sum().sum(),
        df.duplicated().sum()
    ])

audit_df = pd.DataFrame(
    audit,
    columns=[
        "table",
        "rows",
        "columns",
        "nulls",
        "duplicates"
    ]
)

audit_df

               table  rows  columns  nulls  duplicates
0           analysis    21        6      0           0
1       balancesheet  1313       13      0           0
2           cashflow  1188        7      8           0
3          companies    93       12      9           0
4          documents  1586        4     52           0
5   financial_ratios  1184       16    170           0
6         market_cap   552        9      0           0
7        peer_groups    56        4      0           0
8      profitandloss  1277       15    231           0
9        prosandcons    17        4      6           0
10           sectors    92        6      0           0
11      stock_prices  5520        9      0           0