In [1]:
import os

os.chdir(r"C:\Users\ASUS\OneDrive\Desktop\nifty100_project")

print(os.getcwd())

C:\Users\ASUS\OneDrive\Desktop\nifty100_project

In [2]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("database/nifty100.db")

In [3]:
pd.read_sql(
    "SELECT COUNT(*) AS total_companies FROM companies",
    conn
)

   total_companies
0               93

In [4]:
pd.read_sql(
    """
    SELECT *
    FROM companies
    LIMIT 5
    """,
    conn
)

,Mkt Fintech — Nifty 100 | Companies | 92 records,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,id,company_logo,company_name,chart_link,about_company,website,nse_profile,bse_profile,face_value,book_value,roce_percentage,roe_percentage
1,ABB,https://mkt.in/static/mkt-icons/nifty100/ABB.png,Abbott India Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,Abbott India Ltd is one of the leading multina...,https://www.abbott.co.in/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/abb...,10,1657,46,34.9
2,ADANIENSOL,https://m.economictimes.com/thumb/msid-1173715...,Adani Energy Solutions Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,"AESL, part of the Adani portfolio, is a multid...",https://www.adanienergysolutions.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,10,175,9,8.59
3,ADANIENT,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Enterprises Ltd,https://in.tradingview.com/chart/?symbol=ADANIENT,Adani Enterprises Ltd is an Indian multination...,https://www.adanienterprises.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,1,363,11.6,13.64
4,ADANIGREEN,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Green Energy Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,"Adani Green Energy Limited, incorporated in 20...",http://www.adanigreenenergy.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,10,67,96.5,14.7

In [5]:
pd.read_sql(
    """
    SELECT COUNT(*) AS stock_records
    FROM stock_prices
    """,
    conn
)

   stock_records
0           5520

In [6]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("database/nifty100.db")

print("Companies Count")
print(pd.read_sql("SELECT COUNT(*) as cnt FROM companies", conn))

print("\nForeign Key Check")
print(pd.read_sql("PRAGMA foreign_key_check;", conn))

conn.close()

Companies Count
   cnt
0   93

Foreign Key Check
Empty DataFrame
Columns: [table, rowid, parent, fkid]
Index: []

In [7]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("database/nifty100.db")

companies = pd.read_sql(
    "SELECT * FROM companies",
    conn
)

print(companies.head(3))

conn.close()

  Mkt Fintech — Nifty 100  |  Companies  |  92 records  \
0                                                 id
1                                                ABB
2                                         ADANIENSOL

                                          Unnamed: 1  \
0                                       company_logo
1   https://mkt.in/static/mkt-icons/nifty100/ABB.png
2  https://m.economictimes.com/thumb/msid-1173715...

                   Unnamed: 2  \
0                company_name
1            Abbott India Ltd
2  Adani Energy Solutions Ltd

                                          Unnamed: 3  \
0                                         chart_link
1  https://in.tradingview.com/chart/?symbol=NSE%3...
2  https://in.tradingview.com/chart/?symbol=NSE%3...

                                          Unnamed: 4  \
0                                      about_company
1  Abbott India Ltd is one of the leading multina...
2  AESL, part of the Adani portfolio, is a multid...

                              Unnamed: 5  \
0                                website
1              https://www.abbott.co.in/
2  https://www.adanienergysolutions.com/

                                          Unnamed: 6  \
0                                        nse_profile
1  https://www.nseindia.com/get-quotes/equity?sym...
2  https://www.nseindia.com/get-quotes/equity?sym...

                                          Unnamed: 7  Unnamed: 8  Unnamed: 9  \
0                                        bse_profile  face_value  book_value
1  https://www.bseindia.com/stock-share-price/abb...          10        1657
2  https://www.bseindia.com/stock-share-price/ada...          10         175

       Unnamed: 10     Unnamed: 11
0  roce_percentage  roe_percentage
1               46            34.9
2                9            8.59

In [8]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("database/nifty100.db")

companies = pd.read_sql(
    "SELECT * FROM companies",
    conn
)

# Remove first row containing column names
companies = companies.iloc[1:].reset_index(drop=True)

# Rename columns using first data row
companies.columns = [
    'id','company_logo','company_name','chart_link',
    'about_company','website','nse_profile',
    'bse_profile','face_value','book_value',
    'roce_percentage','roe_percentage'
]

companies.to_sql(
    "companies",
    conn,
    if_exists="replace",
    index=False
)

print("New Count:", len(companies))

conn.close()

New Count: 92

In [9]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("database/nifty100.db")

print(
    pd.read_sql(
        "SELECT COUNT(*) as cnt FROM companies",
        conn
    )
)

conn.close()

   cnt
0   92